default:
    py_version: "python3/bin/python"
    rcvr_recode_file: '/Users/mrosen44/OneDrive - Johns Hopkins University/Data_Analysis/IM_Resident_Study/Receiver_codes/Revised_reciever_category_2.xlsx'
    rcvr_recode_file_loc: '/Data/'
    # db_loc: '/Users/mrosen44/Documents/Data_Analysis_Local/RTLS_FB_Reports/'
    db_name: 'rtls_picu'
    db_u: 'postgres'
    db_pw: 'ZNVMDBPld1Mn'
    # tmp_csv_path: '/Users/mrosen44/Documents/Data_Analysis_Local/GEL_RTLS/Data/RTLS_Data/tmp'
    # archive_csv_path: '/Users/mrosen44/Documents/Data_Analysis_Local/GEL_RTLS/Data/RTLS_Data/archive'
    in_path: '/Users/mrosen44/OneDrive - Johns Hopkins University/RTLS_Data/Data_pulls'
    rule_1_thresh: 300
    rule_2_thresh: 180
    rule_2_locs: !expr list('MD Workroom')
    badge_file: '/Users/mrosen44/Johns Hopkins University/Amanda Bertram - Graduate Medical Training Laboratory/RTLS Badge Status.xlsx'
    badge_timeline_dir: !expr getwd()
